from PyQt5.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout, QFrame, QGridLayout, QLabel, QLineEdit, QSpinBox, QComboBox, QPushButton, QTableWidget, QTableWidgetItem, QDoubleSpinBox, QListWidget, QListWidgetItem)
from PyQt5.QtCore import Qt

class BillingUi(QWidget):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window  # Reference to MainWindow for callbacks
        self.theme = main_window.theme
        self.get_button_stylesheet = main_window.get_button_stylesheet
        self.get_section_title_stylesheet = main_window.get_section_title_stylesheet
        self.get_bill_summary_total_stylesheet = main_window.get_bill_summary_total_stylesheet
        self.init_ui()

    def init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 24, 24, 24)
        layout.setSpacing(16)
        # --- Customer Information Section ---
        customer_info_frame = QFrame()
        customer_info_frame.setFrameShape(QFrame.StyledPanel)
        customer_info_frame.setStyleSheet("border: 1px solid #ccc; background: #fff;")
        customer_layout = QGridLayout(customer_info_frame)
        customer_layout.setContentsMargins(12, 12, 12, 12)
        customer_layout.setSpacing(10)
        # Title
        customer_title = QLabel("Customer Information")
        customer_title.setStyleSheet(self.get_section_title_stylesheet())
        customer_layout.addWidget(customer_title, 0, 0, 1, 4)
        # Name & Age
        self.customer_name = QLineEdit()
        self.customer_name.setPlaceholderText("Name")
        self.customer_age = QSpinBox()
        self.customer_age.setRange(0, 120)
        self.customer_age.setPrefix("Age: ")
        customer_layout.addWidget(QLabel("Name:"), 1, 0)
        customer_layout.addWidget(self.customer_name, 1, 1)
        customer_layout.addWidget(QLabel("Age:"), 1, 2)
        customer_layout.addWidget(self.customer_age, 1, 3)
        # Gender & Phone
        self.customer_gender = QComboBox()
        self.customer_gender.addItems(["Male", "Female", "Other"])
        self.customer_phone = QLineEdit()
        self.customer_phone.setPlaceholderText("Phone")
        customer_layout.addWidget(QLabel("Gender:"), 2, 0)
        customer_layout.addWidget(self.customer_gender, 2, 1)
        customer_layout.addWidget(QLabel("Phone:"), 2, 2)
        customer_layout.addWidget(self.customer_phone, 2, 3)
        # Email & Address
        self.customer_email = QLineEdit()
        self.customer_email.setPlaceholderText("Email")
        self.customer_address = QLineEdit()
        self.customer_address.setPlaceholderText("Address")
        customer_layout.addWidget(QLabel("Email:"), 3, 0)
        customer_layout.addWidget(self.customer_email, 3, 1)
        customer_layout.addWidget(QLabel("Address:"), 3, 2)
        customer_layout.addWidget(self.customer_address, 3, 3)
        layout.addWidget(customer_info_frame)
        # --- Main Content Section (Billing Table & Recent Bills) ---
        main_content_layout = QHBoxLayout()
        # Billing Table Section
        billing_table_frame = QFrame()
        billing_table_frame.setFrameShape(QFrame.StyledPanel)
        billing_table_frame.setStyleSheet("border: 1px solid #ccc; background: #fff;")
        billing_table_layout = QVBoxLayout(billing_table_frame)
        billing_table_title = QLabel("Billing Table")
        billing_table_title.setStyleSheet(self.get_section_title_stylesheet())
        billing_table_layout.addWidget(billing_table_title)
        self.billing_table = QTableWidget(0, 6)
        self.billing_table.setHorizontalHeaderLabels([
            "Barcode", "Name", "Quantity", "Price", "Tax", "Discount"
        ])
        self.billing_table.horizontalHeader().setStretchLastSection(True)
        self.billing_table.setAlternatingRowColors(True)
        billing_table_layout.addWidget(self.billing_table)
        # Add/Remove Buttons
        btn_layout = QHBoxLayout()
        self.add_item_btn = QPushButton("Add Item")
        self.add_item_btn.setStyleSheet(self.get_button_stylesheet())
        self.remove_item_btn = QPushButton("Remove Item")
        self.remove_item_btn.setStyleSheet(self.get_button_stylesheet())
        btn_layout.addWidget(self.add_item_btn)
        btn_layout.addWidget(self.remove_item_btn)
        billing_table_layout.addLayout(btn_layout)
        main_content_layout.addWidget(billing_table_frame, 2)
        # Recent Bills Section
        recent_bills_frame = QFrame()
        recent_bills_frame.setFrameShape(QFrame.StyledPanel)
        recent_bills_frame.setStyleSheet("border: 1px solid #ccc; background: #fff;")
        recent_bills_layout = QVBoxLayout(recent_bills_frame)
        recent_bills_title = QLabel("Recent Bills & Drafts")
        recent_bills_title.setStyleSheet(self.get_section_title_stylesheet())
        recent_bills_layout.addWidget(recent_bills_title)
        self.billing_history_list = QListWidget()
        recent_bills_layout.addWidget(self.billing_history_list)
        # Download/Delete Buttons
        history_btn_layout = QHBoxLayout()
        self.download_bill_btn = QPushButton("Download PDF")
        self.download_bill_btn.setStyleSheet(self.get_button_stylesheet())
        self.delete_draft_btn = QPushButton("Delete Draft")
        self.delete_draft_btn.setStyleSheet(self.get_button_stylesheet())
        history_btn_layout.addWidget(self.download_bill_btn)
        history_btn_layout.addWidget(self.delete_draft_btn)
        recent_bills_layout.addLayout(history_btn_layout)
        main_content_layout.addWidget(recent_bills_frame, 1)
        layout.addLayout(main_content_layout)
        # --- Bill Summary Section ---
        bill_summary_frame = QFrame()
        bill_summary_frame.setFrameShape(QFrame.StyledPanel)
        bill_summary_frame.setStyleSheet("border: 1px solid #ccc; background: #fff;")
        bill_summary_layout = QGridLayout(bill_summary_frame)
        bill_summary_layout.setContentsMargins(12, 12, 12, 12)
        bill_summary_layout.setSpacing(10)
        bill_summary_title = QLabel("Bill Summary")
        bill_summary_title.setStyleSheet(self.get_section_title_stylesheet())
        bill_summary_layout.addWidget(bill_summary_title, 0, 0, 1, 2)
        # Subtotal, Tax, Discount, Total
        bill_summary_layout.addWidget(QLabel("Subtotal:"), 1, 0)
        self.subtotal_label = QLabel("₹0.00")
        bill_summary_layout.addWidget(self.subtotal_label, 1, 1)
        bill_summary_layout.addWidget(QLabel("Tax (%):"), 2, 0)
        self.tax_spin = QDoubleSpinBox()
        self.tax_spin.setRange(0, 100)
        self.tax_spin.setSuffix(" %")
        bill_summary_layout.addWidget(self.tax_spin, 2, 1)
        bill_summary_layout.addWidget(QLabel("Discount (₹):"), 3, 0)
        self.discount_spin = QDoubleSpinBox()
        self.discount_spin.setRange(0, 100000)
        bill_summary_layout.addWidget(self.discount_spin, 3, 1)
        bill_summary_layout.addWidget(QLabel("Total:"), 4, 0)
        self.total_label = QLabel("₹0.00")
        self.total_label.setStyleSheet(self.get_bill_summary_total_stylesheet())
        bill_summary_layout.addWidget(self.total_label, 4, 1)
        # Finalize/Save/Print Buttons
        summary_btn_layout = QHBoxLayout()
        self.save_draft_btn = QPushButton("Save Draft")
        self.save_draft_btn.setStyleSheet(self.get_button_stylesheet())
        self.finalize_bill_btn = QPushButton("Finalize Bill")
        self.finalize_bill_btn.setStyleSheet(self.get_button_stylesheet())
        self.print_bill_btn = QPushButton("Print Bill")
        self.print_bill_btn.setStyleSheet(self.get_button_stylesheet())
        summary_btn_layout.addWidget(self.save_draft_btn)
        summary_btn_layout.addWidget(self.finalize_bill_btn)
        summary_btn_layout.addWidget(self.print_bill_btn)
        bill_summary_layout.addLayout(summary_btn_layout, 5, 0, 1, 2)
        layout.addWidget(bill_summary_frame) 