name: Build and Test Medibit Pharmacy

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pytest pytest-qt

      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PyInstaller build
        uses: actions/cache@v4
        with:
          path: |
            build/
            dist/
          key: ${{ runner.os }}-pyinstaller-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pyinstaller-

      - name: Cache Inno Setup
        uses: actions/cache@v4
        with:
          path: C:\ProgramData\chocolatey\lib\innosetup
          key: ${{ runner.os }}-innosetup

      - name: Run Tests
        run: pytest tests/ --disable-warnings -v

      - name: Build EXE and Installer
        run: ./build_installer.bat

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            build/
            *.log
            RELEASE_NOTES.txt
            README.txt
