name: Build, Test, and Release Medibit Pharmacy

on:
  push:
    tags:
      - "v*" # Only run on version tags like v1.0.0
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release name (optional)"
        required: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2022, windows-2019, ubuntu-latest]
        python-version: [3.8, 3.10.11, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pytest pytest-qt pytest-cov flake8 black isort

      - name: Install Inno Setup (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install innosetup --no-progress

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

      - name: Debug Python Path
        run: python -c "import sys; print(sys.path)"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PyInstaller build
        uses: actions/cache@v4
        with:
          path: |
            build/
            dist/
          key: ${{ runner.os }}-pyinstaller-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-pyinstaller-

      - name: Cache Inno Setup
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: C:\\ProgramData\\chocolatey\\lib\\innosetup
          key: ${{ runner.os }}-innosetup

      - name: Debug Path
        run: |
          echo "PWD: $PWD"
          echo "PYTHONPATH: ${{ env.PYTHONPATH }}"
          ls
          ls tests

      - name: Start Xvfb (Linux only)
        if: runner.os == 'Linux'
        uses: GabrielBB/xvfb-action@v1

      - name: Static Analysis - isort
        run: isort --check --diff src/ tests/

      - name: Static Analysis - black
        run: black --check src/ tests/

      - name: Static Analysis - flake8
        run: flake8 src/ tests/

      - name: Run Tests with Coverage
        shell: bash
        run: |
          export PYTHONPATH=src
          python -m pytest --cov=src --cov-report=xml --cov-report=term tests/ --disable-warnings -v

      - name: Build EXE and Installer (Windows only)
        if: runner.os == 'Windows'
        run: |
          ./build_installer.bat

      - name: Build Linux Distribution (Linux only)
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile src/main.py --name medibit-linux
          tar -czvf medibit-linux.tar.gz dist/medibit-linux

      - name: Automated Versioning
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ runner.os }}
          path: |
            dist/
            build/
            *.log
            RELEASE_NOTES.txt
            README.txt
            medibit-linux.tar.gz

      - name: Upload Installer Artifact (Windows only)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: MedibitPharmacySetup
          path: dist/MedibitPharmacySetup.exe

      - name: Upload Linux Artifact (Linux only)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: MedibitLinux
          path: medibit-linux.tar.gz

      - name: Create GitHub Release
        if: github.ref_type == 'tag' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/MedibitPharmacySetup.exe
            medibit-linux.tar.gz
          name: ${{ github.event.inputs.release_name || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
